#page title
page_title                                : Thirteen
# Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 
# Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : 
# Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           
# Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.LukaszDziedziczak.Thirteen                                            
# Enter Google Play Store URL.
presskit_download_link                    :                                         
# Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      
# Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Thirteen                           
# Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           
# Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A card game

enable_smart_app_banner                   : false                                      
# Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Lukasz Dziedziczak                               
your_link                                 : https://lukasz.website                  
your_city                                 : Adelaide
email_address                             : Thirteen.PhoneGame@gmail.com
facebook_username                         :                                           
instagram_username                        : final_synapse
twitter_username                          : FinalSynapse
github_username                           : lukasz-dziedziczak
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :
  - title                                 : Match Making
    description                           : Play online against others via automated match making.
    fontawesome_icon_name                 : star

  - title                                 : Host/Join Matches
    description                           : Host a game or join a match via entering a match code.
    fontawesome_icon_name                 : star

  - title                                 : Bot Matches
    description                           : Train by playing against computer opponents.
    fontawesome_icon_name                 : star

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0.3

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#000000"
app_price_color                           : "#ffffff"
app_description_color                     : "#666666"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
